### PR TITLE
Change style to square Checkbox style

### PR DESCRIPTION
**Pull request by memiks**
Hi,

I modified checkbox style to :
- Change style to real checkbox
- Add onfocus color like button
- Enable usage on Android TV

could solve issue #93 

BR,
Frederic

### CODE REVIEW

**Review by IngoZenz — COMMENTED** [review]
Thank you!
could you attach some screenshots? Also for the different dialogs for filter config and app whitelisting

**Comment by memiks** [comment]
Hi,

One screenshot.
I will add more tomorrow 

Frédéric.


Le 14 septembre 2020 17:23:13 GMT+09:00, IngoZenz <notifications@github.com> a écrit :
>@IngoZenz commented on this pull request.
>
>Thank you!
>could you attach some screenshots? Also for the different dialogs for filter config and app whitelisting
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/IngoZenz/personaldnsfilter/pull/110#pullrequestreview-487524986
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by IngoZenz** [comment]
I do not like the transparent background of the check box...
Coud you make it like this?
image

**Comment by IngoZenz** [comment]
It is fine - will do some chnages on top

**Comment by memiks** [comment]
No problem I am in Tokyo, so we have some times lag I think.
Thanks to merged and update style.

I will make some others changes to have a banner for Android TV and let application usable with remote.

I will give you screenshots and explanation before pull request if you want ?

Best Regards,
Frederic.

**Comment by IngoZenz** [comment]
ok - Thanks - pleae keep it simple

**Pull request merged**
