### PR TITLE
minor Bug fix

### PR DESCRIPTION
**Pull request by j-moriarti**
- Fixed a minor bug in displaying current work directory for non-Android builds.

### CODE REVIEW

**Comment by IngoZenz** [comment]
This won't work on Android 👎 
Sorry ;-)
Ingo

**Comment by j-moriarti** [comment]
OMG! you were faster than me :) I was just going to close this!
sorry for messing things :)

**Comment by IngoZenz** [comment]
No Problem at all :-)

 
 

Gesendet: Dienstag, 30. Juni 2020 um 16:30 Uhr
Von: "j-moriarti" <notifications@github.com>
An: "IngoZenz/personaldnsfilter" <personaldnsfilter@noreply.github.com>
Cc: "IngoZenz" <i.z@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [IngoZenz/personaldnsfilter] minor Bug fix (#92)


 

OMG! you were faster than me :) I was just going to close this!
sorry for messing things :)

**Comment by j-moriarti** [comment]
> 
> 
> This won't work on Android -1
> Sorry ;-)
> Ingo

What about the following code? :

```
if ("".equals(WORKDIR))
	Logger.getLogger().logLine("Using Directory: " + System.getProperty("user.dir")); // for non-Android
else
	Logger.getLogger().logLine("Using Directory: " + WORKDIR); // for Android
```

tested successfully on Linux mint 19, Windows 10, and Android 7.

**Comment by IngoZenz** [comment]
Will propose s.th...
At the end we shall ensure WORKDIR is set correctly in the non android case.
Guess it should be implemented in the ExecutionEnvironment impl for Standalone case. I think it is implemented in DNSFilterProxy

**Comment by IngoZenz** [comment]
You can set WORKDIR within DNSFilterProxy.java main method. It is the entry point for the non Android version

**Pull request closed without merging**
